### PR TITLE
Clear all cached outputs when reloading script

### LINKED ISSUE #15: Possible memory leak when reloading script
Steps to replicate:

- Press CTRL+R
- Profit
- Realise that buying more ram was not the solution
- Loss

It appears that, upon reloading, some buffer isn't flushed, and all ram that was in use by vapoursynth-preview isn't freed. This therefore starts to cause problems after multiple refreshes, where vapoursynth-preview can end up using all of my system memory. I have tried (though only for a little bit) to find the source of the problem, though I'm unsure exactly where it could be. This has been an issue on all systems I've tested in the last few months, both unix based (arch) and Windows, at current git head.

I will do some more work to try to trace the issue when I have time.

Cheers

### PR DESCRIPTION
**Pull request by AkarinVS**
It should fix the memory leak when reloading script.

Fixes #15.

Signed-off-by: akarin <i@akarin.info>

### CODE REVIEW

**Comment by AkarinVS** [comment]
FYI.

An easy way to test if there is any filter memory leak is to run vsp under gdb/lldb with the following script and set a breakpoint on `blankClipFree`:
```py
import vapoursynth as vs
core = vs.core

clip = core.std.BlankClip()
clip.set_output()
```

When reloading the script, the debugger should hit the breakpoint if things are working properly.
Without this PR, you will observe that there is no call to `blankClipFree` ever, suggesting that filters are leaking due to vsp incorrectly retaining clip references somewhere.

**Comment by Endilll** [comment]
It feels like `Output` or `Outputs` are leaked, so they continue to hold references to `VideoNode`s. I'm investigating it.
Thank you for pointing out to this.

**Comment by AkarinVS** [comment]
Note that my PR already identified and fixed all the leaks.

>

**Comment by Endilll** [comment]
This PR fixes leak of `VideoNode` references, but it doesn't address the issue that `Output` object that hold those are alive after reloading.

**Comment by AkarinVS** [comment]
Those alive Output objects are harmless, in fact, if we also remove those,
after reload vsp will not remember the previous outputs.

**Comment by Endilll** [comment]
It was too hard for me to agree on breaking an invariant that `Output` objects always hold `VideoNode`(s) for a given output, so I made sure `Output` object themselves are all dead by the time new script is evaluated. No `VideoNode` is leaked on reload now.

I usually have hard time with debuggers, so I inserted some prints into cython wrapper to trace VideoNode construction and destruction.

Again, thank you for convincing me that it's possible to make reloading work, otherwise I wouldn't be able to dedicate the whole evening on this. Please, close this PR if you don't have further comments on this topic.

**Comment by AkarinVS** [comment]
thanks for fixing this issue properly. please remember to close #15.

**Pull request closed without merging**
