### PR TITLE
Add VSCode Install and Configuration Guide

### LINKED ISSUE #12: Create comprehensive installation guide
Can you create a step-by-step walkthrough for how to install this? 

Been trying to figure it out with someone who has an older version installed and it doesn't seem to work the same. 

As this isn't a normal extension (or doesn't appear to be), it's not exactly self-evident how this should be setup without instructions. 

Items that would be good to know:
1. where to install
2. how to install
3. how to configure .vpy files to use this by default
4. how to configure this globally so that individual workspaces/folders don't need a copy
5. how to configure the terminal settings in vscode to use this properly

Items which might be complicating this for me:
1. using Windows
2. using python installed locally, not via mingw or other means
3. my default integrated terminal is Powershell (used for work, so not going to change but others might be in similar situations)

### PR DESCRIPTION
**Pull request by begna112**
Resolves https://github.com/Endilll/vapoursynth-preview/issues/12

Created a guide.

### CODE REVIEW

**Comment by Endilll** [comment]
So you had no luck with built-in user-level tasks in recent versions of VS Code?
Sorry for the late answer.

**Comment by NSQY** [comment]
I have followed this just now when re-creating my VSCode environment (1.56.2). All is well, thank you. The tip about the 'Global Config' plugin is very useful.

**Comment by begna112** [comment]
> So you had no luck with built-in user-level tasks in recent versions of VS Code?
> Sorry for the late answer.

honestly, I'd need you to be more explicit on what you're talking about. This is the only way I've found to make it work.

**Comment by Endilll** [comment]
I mentioned them in #12.
https://code.visualstudio.com/updates/v1_42#_user-level-tasks

**Pull request closed without merging**
